<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>The scope selectors may seem inappropriate, but should map on many color schemes</string>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>blockml</string>
	</array>
	<key>keyEquivalent</key>
	<string>^~B</string>
	<key>name</key>
	<string>BlockML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#inlineCode</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#code</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#section</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#block</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>block</key>
		<dict>
			<key>begin</key>
			<string>(\[|\b\w*\[)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>constant.other.block.blockml</string>
			<key>end</key>
			<string>(\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<key>code</key>
		<dict>
			<key>begin</key>
			<string>(code\[)(.*)(\]\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>constant.other.block.blockml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Turns comments in code tags into normal text</string>
			<key>contentName</key>
			<string>constant.other.block.blockml</string>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>comment</key>
			<string>The pattern matches comments within comments like /*.../*comment*/...*/ </string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.blockml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
			</array>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\.</string>
			<key>name</key>
			<string>escape</string>
		</dict>
		<key>inlineCode</key>
		<dict>
			<key>begin</key>
			<string>(c\[)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Turns comments in inlineCode tags into normal text</string>
			<key>contentName</key>
			<string>constant.other.block.blockml</string>
			<key>end</key>
			<string>(\])</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
			</array>
		</dict>
		<key>section</key>
		<dict>
			<key>begin</key>
			<string>(sec\[)(.*)(\]\[)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>string.heading.blockml</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>section.blockml</string>
			<key>end</key>
			<string>(\])</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.markup.blockml</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.blockml</string>
	<key>uuid</key>
	<string>B08278A0-1742-4B5B-8D23-268784C45423</string>
</dict>
</plist>
