<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
		<string>blockml</string>
	</array>
	<key>foldingStartMarker</key>
	<string>/\*|\[\s*$</string>
	<key>foldingStopMarker</key>
	<string>\*/|^\s*\]</string>
	<key>name</key>
	<string>BlockML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#markup</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#escape</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#link</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#noSpellChecking</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;=sec\[)</string>
			<key>end</key>
			<string>(?=\])</string>
			<key>name</key>
			<string>string</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>^([ \t]*)(?=\S)</string>
			<key>contentName</key>
			<string>text</string>
			<key>end</key>
			<string>^(?!\1(?=\S))</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#markup</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comment</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#escape</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#link</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#noSpellChecking</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<key>escape</key>
		<dict>
			<key>match</key>
			<string>\\+.</string>
			<key>name</key>
			<string>escape</string>
		</dict>
		<key>link</key>
		<dict>
			<key>match</key>
			<string>(?x)
					( (https?|s?ftp|ftps|file|smb|afp|nfs|(x-)?man|gopher|txmt)://|mailto:)
					[-:@a-zA-Z0-9_.,~%+/?=&amp;#]+(?&lt;![.,?:])
			</string>
			<key>name</key>
			<string>link</string>
		</dict>
		<key>markup</key>
		<dict>
			<key>match</key>
			<string>\[|\]|\b\w*\[</string>
			<key>name</key>
			<string>markup</string>
		</dict>
		<key>noSpellChecking</key>
		<dict>
			<key>begin</key>
			<string>(?&lt;=id\[)</string>
			<key>end</key>
			<string>(?=\])</string>
			<key>name</key>
			<string>noSpellChecking</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.blockML</string>
	<key>uuid</key>
	<string>B08278A0-1742-4B5B-8D23-268784C45423</string>
</dict>
</plist>
